apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2026-05-05T06:25:38Z"
  name: units-api
  namespace: default
  resourceVersion: "478681"
  uid: e38b9bec-88a8-4eed-a88c-58234397187d
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: units-api
status:
  conditions:
  - lastTransitionTime: "2026-05-05T06:25:53Z"
    message: recommended size matches current size
    reason: ReadyForNewScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2026-05-05T16:33:47Z"
    message: the HPA was able to successfully calculate a replica count from cpu resource
      utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2026-05-05T06:50:42Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentMetrics:
  - resource:
      current:
        averageUtilization: 49
        averageValue: 49m
      name: cpu
    type: Resource
  currentReplicas: 2
  desiredReplicas: 2
  lastScaleTime: "2026-05-05T16:52:35Z"